# SPDX-FileCopyRightText: 2023 Oscar Bender-Stone <oscarbenderstone@gmail.com>
# SPDX-License-Identifier: CC-BY-4.0
#+title: Contributing Guidelines

* TODO Determine Full Contributing Guidelines
* Style
** LaTeX
- As a standard format for academic papers, we will use: TBD
** References
* Translation (Needed)
I am looking to translate this entire repo into different languages. Please contact me if you would like to help in this effort!
* Copyright and Licensing
- Whenever you create a new file, please follow the [[https://reuse.software/spec/][REUSE specification, version 3.0.]] In particular, at the top of the file, you should add a SPDX-FileCopyRightText and SDPX-License-Identifier in comments.
- If you are /changing/ or /adding/ to a file, add your own SPDX-FileCopyRightText tag below prexisting ones (/but/ above SPDX-License-Identifier). In case you would like to use a different license for a section YOU create, *you must add comments between your contributions, with the SPDX-FileCopyRightText and SPDX-License-Identifier tags*
- You may apply a license that is compatible with and provides all of the rights of CC-BY-4.0. If you add a new license, be sure to add it under LICENSES or raise an issue.
