(TeX-add-style-hook
 "3-spec"
 (lambda ()
   (TeX-add-symbols
    "chars"
    "numbers"
    "whitespaces"
    "reserved"
    "strings"
    "term"
    "terms"
    "delimiters"
    "escapes"
    "encoding"
    "decoding"
    "can"
    "bnfs"
    "scope")
   (LaTeX-add-labels
    "sec:conformance"
    "examples:encodings"
    "section:customization"
    "section:conformance"
    "section:syntax"
    "table:grammars"
    "def:unit-graph"
    "def:wig"
    "req:labels"
    "lemma:closure"
    "def:iso"
    "sec:bootstrap"
    "sec:validator"))
 :latex)

